@dotnet_external_secrets_demo_HostAddress = http://localhost:5051

GET {{dotnet_external_secrets_demo_HostAddress}}//not-so-secret/from-disk/
Accept: application/json

###

GET {{dotnet_external_secrets_demo_HostAddress}}//not-so-secret/from-environment/
Accept: application/json
